[tool.poetry]
name = "djangorest"
version = "0.1.0"
description = ""
authors = ["Leo-ui-582 <lipovetskiy88@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
